### ISSUE TITLE
TESpy has moved into the oemof cosmos!

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/tespy#1]
Hi everybody,

we have now moved the first version of the TESpy package into the oemof-cosmos.

I have created a group @oemof/oemof-tespy and added some people who might be involved within the development process!

@fwitte will keep on developing here with the major goal to provide a stable version.

Merry christmas to everyone!
Cord

**Comment by uvchik** [comment]
@fwitte Welcome to the oemof cosmos. I really appreciate your contributions.
