### ISSUE TITLE
Networks with small massflow do not converge

### ISSUE THREAD

**Issue by stianchris** [oemof/tespy#117]
In a solar air thermal collector with leakage of air, no solution was found, as the massflow in kg/s was too low. In such cases, newton-raphson does not converge. Possible solution would be to check for parameters, that are below a specific limit and in such cases, switch the calculation to a different unit for this parameter. In the example: switch the unit of the massflow to g/s. This needs to be done internally and not just in the unit-definition in the setup of the network.

**Comment by fwitte** [comment]
Thanks for you report @stianchris, can you provide an example script showing the behavior?
