### ISSUE TITLE
Version incompatibility w/ Python 3.8 (due to CoolProp)

### ISSUE THREAD

**Issue by arosen93** [oemof/tespy#176]
Python 3.8 leads to an import issue with CoolProp 6.3.0, as noted [here](https://github.com/CoolProp/CoolProp/issues/1876), and by extension the installation instructions for tespy do not necessarily lead to a successful build as-specified. This issue should be resolved in the dev version (CoolProp 6.3.1). It might be useful to mention this in the documentation (at least until CoolProp 6.3.1 is uploaded to PyPI), specify that `python=3.7` should be used (especially if building a new Anaconda environmnt), or mention that CoolProp should be installed from the up-to-date source if the import error appears.

**Comment by fwitte** [comment]
Thank you for your hint, I will update the setup.py on the dev-branch to require python <= 3.7.
