### ISSUE TITLE
Ice Storage- how to consider enthalpy of fusion

### ISSUE THREAD

**Issue by MrNleGrande** [oemof/tespy#184]
Hey guys,

I'm just getting started using TESPy. 
I used your tutorial for building up a heat pump system and adjusted it to my preferences. Now I wanna add an ice storage in one of my heat exchangers. However, I'm struggling to keep the temperature at 0 degrees while considering the enthalpy of fusion.

Do you know any workaround for that problem?

Best
Nils

**Comment by fwitte** [comment]
Hi Nils,
nice to hear you are considering TESPy for your work. Most likely, the issue here is that the fluid property database integrated (CoolProp, data for water to be found here: http://www.coolprop.org/fluid_properties/fluids/Water.html#fluid-water) does not support temperature inputs at/below melting point. In order this issues regarding the limits of the fluid properties (generically), there are methods implemented in the TESPy solver iteration that prevent pushing fluid property values out of the feasible range. Therefore, the network will never converge for a temperature input of water at 0°C.

If I understand correctly, you want to use liquid water at freezing point as your heat source? If so, it might be possible to use the heat_exchanger_simple component for the superheater and the evaporator. Then calculate the change in the state of the freezing water externally. It would be best, if you can provide an example code, so I can have a look into it.

Have a nice weekend, best regards
Francesco

**Comment by fwitte** [comment]
> Thank you very much for your suggestion. I don't know why I didn't come up with that idea but the solution looks actually as simple as that. It works just perfect now.

Great!

> From my current point of view, I can simply use connection data as input to my models and use the output data at the output connection? Or does the solver throw any error then?

What do you mean with this exactly? If you want to use the fluid state at a connection as an input for your dynamic model and specify the output state from your results, this might work. But this will not work for mass flow, as the governing equations imply no change in mass flow. Given the fact, you fetch a fluid's state and calculate the output state in a different model, will your TESPy model only serve for postprocessing? Maybe you can give me some more details. I would be curious if there is a way to couple TESPy with dynamic simulations.

Cheers

**Comment by MrNleGrande** [comment]
> Given the fact, you fetch a fluid's state and calculate the output state in a different model, will your TESPy model only serve for postprocessing?

Now I don't know if I understood correctly, but let me try to explain further.

Let's take the heat pump system, including an ice storage for low temperature heat supply in the evaporator. With TESPy, I can now calculate a stationary working point. But now let's imagine, I want to include a fluctuating power supply, a wind farm or so, to power the system. 
Additionally to the components working in part load, I expect influence of thermal inertia in the piping system, the heat exchangers and the ice storage. Those influence I want to capture by dynamic models of the corresponding components because as far as I know its not included currently.
So, in my idea, I loop over TESPy, accounting for the time-dependant energy supply, and thus calculating "stationary points" but in some components considering time-dependant effects such as heat loss, etc. The mass flow should be no issue here, is it?

Hope this explanation helps a little.

Best

**Comment by fwitte** [comment]
Yes, it does help very much.

> So, in my idea, I loop over TESPy, accounting for the time-dependant energy supply, and thus calculating "stationary points" but in some components considering time-dependant effects such as heat loss, etc. The mass flow should be no issue here, is it?

Sounds nice. In case you will publish your research, I would be interested to see, what the results are.

Your plans should definitively work. One of the issues could be facing is instability when many input parameters change by a lot and simultaneously from one timestep to the next one. I am not sure, if this will be a problem in your application.

So, I usually solve this problem, by stepwise approaching of the target operation point. For example, in a project we are coupling TESPy and OGS (OpenGeoSys) to simulate the operation of thermal storages. For every time step (usually hourly, may be different of course) there is a target heat transfer rate from/to storage along with temperature levels on the heating system side. When jumping from one hour at full load to the next hour at minimum load and large deviation in temperature levels, I proceed to first adjust the temperature levels (e.g. in increments of 3 K) and afterwards the heat transferred (e.g. in increments of 10 % of nominal load or in logarithmic steps).

Have a nice week!

**Comment by MrNleGrande** [comment]
Thank you very much for your response! It will definetly help for upcoming issues.

I will let you know when the output is publishable.

Best

**Comment by fwitte** [comment]
Closing this issue, since it is resolved.
