### ISSUE TITLE
Track equations with respective connection or component and the related connections causing singularity in Jacobian

### ISSUE THREAD

**Issue by MrNleGrande** [oemof/tespy#187]
Hey Francesco, 

Today I like to come up with another issue bothering me since some days. 
I'm using TESPy for a heat pump system and adjusted the example to my needs and it works just perfect. 
I replaced the expansion valve with a turbine in order to recuperate some energy. Now I want to add a condenser just behind the turbine to reach a liquid state, so the following evaporation from the ice storage is more effective (produces more cold).

I'm using the same parameter set as I did before but no the network doesn't converge. 
Do you think the problem is caused by the state between turbine and condenser being in the two-phase region?

Also I like to know whether it's possible to track exactly which component/connection caussed the issue.

Thanks for your support again!

Best
Nils

**Comment by fwitte** [comment]
Hi Nils,

are you maybe interested to work on this together? Write me an e-mail an we can talk about it via Skype/phone/...: francesco.witte@hs-flensburg.de. 

> I replaced the expansion valve with a turbine in order to recuperate some energy. Now I want to add a condenser just behind the turbine to reach a liquid state, so the following evaporation from the ice storage is more effective (produces more cold).
> 

But where do you dump the heat in the first place? You'll need a cooling source which is at an even lower temperature level as the ice storage, why wouldn't you directly extract heat from your ice storage in that case?

> I'm using the same parameter set as I did before but no the network doesn't converge.
> Do you think the problem is caused by the state between turbine and condenser being in the two-phase region?

Hard to say, I'll need to have a look at the plant.
 
> Also I like to know whether it's possible to track exactly which component/connection caussed the issue.

It would be possible to detect the equations producing a linear dependency and which connections are affected by the given equation. In case you do not have row or column with zeros only in the Jacobian, there also would be a second row/column at minimum. Maybe there is a way of outputting these information.

Best
Francesco

**Comment by fwitte** [comment]
Closing this, since I do not have time to investigate... If someone else does want to give it a try we can reopen.
