### ISSUE TITLE
Remove the Python 3.7 restriction

### ISSUE THREAD

**Issue by jowr** [oemof/tespy#195]
Hi, just wanted to let you know that I have added Python 3.8 builds for CoolProp 6.4. We are planning a release within the next 48h and you might want to take care of this before releasing the next version of your software.

https://github.com/CoolProp/CoolProp/issues/1929
https://github.com/CoolProp/CoolProp/issues/1928

**Comment by fwitte** [comment]
Hi,
great, thank you very much for letting me know!
Have a nice week!

**Comment by fwitte** [comment]
Resolved.
