### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by GerfriedC** [oemof/tespy#217]
On a WSL with ubuntu 18, the pip install tespy asks for python 3. Of course, it was installed as 3.6 . May be a path problem?
thanks

**Comment by fwitte** [comment]
Hi, can you provide the error message? I suspect, your pip command is pointing to a python 2.x installation. You may try the following instead:
- `python3.6 -m pip install tespy` or 
- `python3 -m pip install tespy`

depending on how the symbolic link to your python 3.6 installation is called.

**Comment by fwitte** [comment]
Hi @GerfriedC,
has your issue been resolved?
Best

**Comment by palmipete** [comment]
Dear all,
I have python 3.8 installed (Python 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0] on linux)
and get the following message when I try to install:
command used: python3.8 -m pip install tespy
answer:
ERROR: Could not find a version that satisfies the requirement tespi (from versions: none)
ERROR: No matching distribution found for tespi

do I need a lower version of Python or is there any chance to succeed in the installation?
Thank you for your help !!
Peter

**Comment by fwitte** [comment]
Hi Peter,

your error messages indicate, that you installed **tespi** instead of **tespy**. Maybe just a typo?
```
ERROR: Could not find a version that satisfies the requirement tespi (from versions: none)
ERROR: No matching distribution found for tespi
```
Best
Francesco

**Comment by palmipete** [comment]
Hi Francesco. wow, I like easy problems, but this was really stupid ;-)
thank you
Peter
