### ISSUE TITLE
Stick closer to PEP8

### ISSUE THREAD

**Issue by p-snft** [oemof/tespy#218]
Diving into TESPy, I found that TESPy is rather reluctant with its code style. Sticking closer to PEP8 might help users e.g. distinguishing class names (CamelCase) from function names (snake_case).

**Comment by fwitte** [comment]
> Diving into TESPy

Nice!

> I found that TESPy is rather reluctant with its code style. Sticking closer to PEP8 might help users e.g. distinguishing class names (CamelCase) from function names (snake_case).

I like your proposed changes, I will see, when I have time to implement those. If anybody is interested in checking for style guidelines (maybe a possible Do-a-thon for https://github.com/oemof/oemof/issues/80, what do you think?), I would be very happy to give support.

**Comment by p-snft** [comment]
For at least solph and network, we stick rather close to the style guides and also have automatic checks. As refactoring at this level does not profit too much from collaboration, I would recommend these digital helpers over a session at the dev meeting.

Maybe, we just open a branch with style testing (@uvchik might have advice) and invite less experienced users (like me) to join in fixing the issues that pop up.
