### ISSUE TITLE
Fail to implement small heat pump model due to singularity

### ISSUE THREAD

**Issue by alicia-le** [oemof/tespy#231]
Within a semester project at my university, I am currently using TESPy. The goal of the project is to "translate" the results of an optimization for the setup of a district heating network into a TESPy model. Basically, the optimization outputs the capacities of the different components for heat supply (e.g., heat pump, gas boiler and gas CHP).
In the first step, I want to set up the components as different subsystems as simple as possible. However, I am not able to do so as I always get the error message "singularity in Jacobian matrix". Is there a way to find out from which components and equations the singularity arises?

In the following, I attached the code for the heat pump I set up. It is an air-sourced heatpump that uses ammonia. As "fixed" parameters from the preceeding opimization, I know that Q_cd=40000, P_cp = 13000. The flow temperature on the consumer side after the condenser should be 80°C. All other parameters can be chosen freely.

[heatpump_simple.zip](https://github.com/oemof/tespy/files/5475661/heatpump_simple.zip)

**Comment by fwitte** [comment]
Hi @alicia-le,
unfortunately due to the nature of the implicit equation formulation in newton's method, there is not really a generic way of determining the "bad" parameters. I really recommend you build up your script step by step to determine which parameters you want to set and which parameters are a result. For larger networks I usually draw a flow chart of my plant and write down the parameters I want to have and which parameters are a result from my specifications.

Quickly looking at your script, I see the following "issues":
- switched sides of the evaporator (hot side should be ambient air -> in1/out1)
- typo in fluid vector on ai_ev (NH3 missing)
- temperature after valve specified directly and indirectly using ttd_l at the evaporator.
- temperature after the condenser not set to 80 (?)
- state of the working fluid is not really determined after evaporation (seems somewhat strange to me, e.g. set Td_bp=... to make sure not to stay in two-phase region still)

Best regards
Francesco

You could try something like this:

```
"""
TESPy subsystem heatpump
"""

from tespy.networks import network
from tespy.components import (source, sink, cycle_closer, valve,
                              compressor, condenser, heat_exchanger)
from tespy.connections import connection
from tespy.tools.characteristics import char_line
from tespy.tools.characteristics import load_default_char as ldc

# NETWORK ######################################################################
nw = network(fluids=['air', 'NH3', 'water'],
             T_unit='C', p_unit='bar', h_unit='kJ / kg', m_unit='kg / s')

# COMPONENTS ###################################################################
# sources & sinks
cool_closer = cycle_closer('coolant cycle closer')
cool_source = source('coolant source')
cool_sink = sink('coolant sink')

cons_back = source('consumer back flow')
cons_feed = sink('consumer feed flow')

amb_in = source('ambient air source')
amb_out = sink('sink ambient air')

# components
cd = condenser('condenser')
va = valve('valve')
ev = heat_exchanger('evaporator')
cp = compressor('compressor')

# CONNECTIONS ##################################################################
cc_cd = connection(cool_closer, 'out1', cd, 'in1')

cb_cd = connection(cons_back, 'out1', cd, 'in2')
cd_cf = connection(cd, 'out2', cons_feed, 'in1')

cd_va = connection(cd, 'out1', va, 'in1')

va_ev = connection(va, 'out1', ev, 'in2')

ai_ev = connection(amb_in, 'out1', ev, 'in1')
ev_ao = connection(ev, 'out1', amb_out, 'in1')

ev_cp = connection(ev, 'out2', cp, 'in1')

cp_cc = connection(cp, 'out1', cool_closer, 'in1')

nw.add_conns(cc_cd, cb_cd, cd_cf, cd_va, va_ev, ai_ev, ev_ao, ev_cp, cp_cc)

# COMPONENT PARAMETRIZATION ####################################################
# condenser
cd.set_attr(pr1=0.99, pr2=0.99, ttd_u=5, design=['pr1', 'ttd_u'],
            offdesign=['zeta2', 'kA'])

# evaporator system
kA_char1 = ldc('heat exchanger', 'kA_char1', 'DEFAULT', char_line)
kA_char2 = ldc('heat exchanger', 'kA_char2', 'EVAPORATING FLUID', char_line)

ev.set_attr(pr1=0.99, pr2=0.99,
            kA_char1=kA_char1, kA_char2=kA_char2,
            design=['pr1', 'ttd_l'], offdesign=['zeta1', 'kA'])

# compressor
cp.set_attr(design=['eta_s'], offdesign=['eta_s_char'])

# CONNECTION PARAMETRIZATION ###################################################
# coolant closer -> condenser
cc_cd.set_attr(fluid={'air': 0, 'NH3': 1, 'water': 0})

cb_cd.set_attr(T=60)
cd_cf.set_attr(fluid={'air': 0, 'NH3': 0, 'water': 1}, p=10, T=80)


# evaporator system cold side
va_ev.set_attr(T=10, p0=5)
ev_cp.set_attr(state='g', Td_bp=5)

# evaporator system hot side
ai_ev.set_attr(T=15, p=1, fluid={'air': 1, 'NH3': 0, 'water': 0})
ev_ao.set_attr(T=10)


# KEY PARAMETER ################################################################

cd.set_attr(Q=-40000)
cp.set_attr(P=13000)

# SOLVING ######################################################################
nw.solve('design')
nw.print_results()

```

**Comment by alicia-le** [comment]
Hey Francesco, thank you for your help! I got it working as a subsystem now as well...

**Comment by fwitte** [comment]
Good to hear that @alicia-le, have fun working with TESPy :)
