### ISSUE TITLE
'' hydro_group'' could not be able to be used in subsystems

### ISSUE THREAD

**Issue by ShuangChen88** [oemof/tespy#24]
While running a btes network script(please see in attachment) with using a predefined subsystem, The 
following error messages from the TESPy will be caused when the pipeline attribute is specified with "hydro_group ='HW''' in the subsystem:

< if np.isnan(kwargs[key]):
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''>

I'm not sure if an attribute with string type or an attribute with data_container likes ''dc_gcp''  is supported for the input types in a subsystem or not.  Could you please be kindly to give your opinions on that.

[btes_script.txt](https://github.com/oemof/tespy/files/2219386/btes_script.txt)
[sub_btes_para.txt](https://github.com/oemof/tespy/files/2219383/sub_btes_para.txt)

**Comment by fwitte** [comment]
Hi Shuang,
thanks for reporting that bug, I will have to make updates to the subsystems module to make this work. A fast workaround would be something like this:
```
for pipe in bo.btes:
    pipe.set_attr(hydro_group='HW')
```
This iterates through all the subsystem's btes-pipes and sets the hydro_group parameter. I runned the script with these changes and had some convergence issues, as the mass flow values were negative after the first iteration. I added this line in the tespy.networks module at the convergence check:
```
if c.m.val_SI < 0:
    c.m.val_SI *= -1
```
In order to use that check out the features/improve_convergence_stability branch.
I hope that works for you, have a nice week!
Francesco

**Comment by ShuangChen88** [comment]
Dear Francesco,

Thanks for your help. It works now.:)

Have a nice week!
Shuang

**Comment by fwitte** [comment]
Hi Shuang,
it is now possible to provide keywords for subsystems with values that are of type str on the dev branch (321308f0654c1e060f18166bf4127a4142b22133). Your __init__ in the example will have to look like this now (according to the pattern of the subsystems.subsystem.__init__ method):
```
    def __init__(self, label, num_btes, **kwargs):

        if not isinstance(label, str):
            raise MyComponentError('Subsystem label must be of type str!')

        elif len([x for x in [';', ', ', '.'] if x in label]) > 0:
            raise MyComponentError('Can\'t use ' + str([';', ', ', '.']) + ' ',
                                   'in label.')
        else:
            self.label = label

        if num_btes <= 1:
            raise MyComponentError('Minimum number of compressors is 2.')
        else:
            self.num_btes = num_btes

        # set default values
        for key in self.attr():
            self.__dict__.update({key: np.nan})
            self.__dict__.update({key + '_set': False})

        self.subsys_init()
        self.set_attr(**kwargs)
```
The issue should be resolved by this and the workaround is not necessary anymore.
Have a nice week!

**Comment by ShuangChen88** [comment]
Dear Francesco,

Thank you for your fixing. I've test my script and it works well now.

Best regards,
Shuang
