### ISSUE TITLE
Tiny deviation in calculation of Darcy friction factor?

### ISSUE THREAD

**Issue by stianchris** [oemof/tespy#254]
Hello Francesco,

I'm just checking my model and I stumbled upon a tiny deviation in the formula for the darcy friction factor in comparison to the literature mentioned (https://tespy.readthedocs.io/en/master/api/tespy.tools.html#tespy.tools.helpers.darcy_friction_factor and same for the code https://tespy.readthedocs.io/en/master/_modules/tespy/tools/helpers.html#darcy_friction_factor in comparison to VDI Wärmeatlas, 2018):

Blasius according to VDI is relevant for Re ~3000 to 100,000 (10^5), for 10^4 < Re < 10^6 Hanakov is relevant. In the tespy documentation, Hanakov is used for 10^5 < Re < 5*10^6; in the tespy code Hanakov is used for 5*10^4 < Re < 10^6:
            if re <= 5e4:
                return blasius(re)
            elif re < 1e6:
                return hanakov(re)

Did I oversee something?
I guess it does not really affect the results...

Kind regards,

Christian

**Comment by fwitte** [comment]
Hi Christian,
thank you very much for reporting. I checked it for several values of Reynolds and there is indeed a small difference. I fixed it and uploaded the code to the dev branch, changes go on PyPI with the next release.
Best
Francesco

**Comment by stianchris** [comment]
Nice! and quick as always ;)

**Comment by fwitte** [comment]
How did you even spot that? :D
