### ISSUE TITLE
Undocumented ttd_u/ttd_l parameters

### ISSUE THREAD

**Issue by jelic1marko** [oemof/tespy#259]
During the process of recreating systems from example scripts, as well as developing my own networks, I have noticed that there are a few parameters available to be set, but not listed in the documentation of the corresponding classes.

Namely, upper and lower terminal temperature difference values (ttd_u and ttd_l) are available to be set as attributes for instances of classes Condenser and Heat Exchanger as is demonstrated in one of the [air heat pump examples](https://github.com/oemof/oemof-examples/blob/master/oemof_examples/tespy/heat_pump/heat_pump_air.py) and is given by
`cd = Condenser('condenser')`
`ev = HeatExchanger('evaporator')`
[...]
`cd.set_attr(pr1=0.99, pr2=0.99, ttd_u=5, design=['pr2', 'ttd_u'], offdesign=['zeta2', 'kA_char'])`
`ev.set_attr(pr1=0.999, pr2=0.99, ttd_l=5, kA_char1=kA_char1, kA_char2=kA_char2, design=['pr1', 'ttd_l'], offdesign=['zeta1', 'kA_char'])`
while the [documentation for the Condenser class](https://tespy.readthedocs.io/en/master/api/tespy.components.html#tespy.components.heat_exchangers.condenser.Condenser) and the [documentation for the Heat Exchanger class](https://tespy.readthedocs.io/en/master/api/tespy.components.html#tespy.components.heat_exchangers.heat_exchanger.HeatExchanger) don't show ttd_u and ttd_l as available parameters, but only lists the corresponding equation. 

Was this done intentionally for some reason or was it overlooked by mistake?

**Comment by fwitte** [comment]
That was indeed overlooked... Thank you for the find!

**Comment by jelic1marko** [comment]
> That was indeed overlooked... Thank you for reporting!

That was my assumption, kind of confused me at first, but since I saw that it works just fine, I continued using it normally...

**Comment by fwitte** [comment]
Resolved by #260
