### ISSUE TITLE
Missing char_map_func() documentation for Compressor

### ISSUE THREAD

**Issue by jelic1marko** [oemof/tespy#262]
The Compressor module appears to implement a function char_map_func() that is denoted in the [documentation](https://tespy.readthedocs.io/en/master/api/tespy.components.html#module-tespy.components.turbomachinery.compressor) however, unlike other functions/equations of the compressor (e.g. pr_func() or eta_s_char_func()), the "tespy.components.turbomachinery.compressor.Compressor.char_map_func()" label does not appear to be a (hyper)link but rather static text. On the other hand, searching the documentation for "char_map_func()" appears to return no direct results but rather points to other methods like 

- "[...].Compressor.char_map_pr_func", 
- "[...].Compressor.char_map_eta_s_func" and 
- "[...].Compressor.char_map_pr_func_doc" 

hinting at (what I suppose are) specific implementations of a char_map_func() equation (see image below). 

Should these specific implementatons potentially be documented in a centralized place that refers to how char_map_func() could be utilized to calculate pr or eta_s based on a characteristic map?

![image](https://user-images.githubusercontent.com/20132076/115570645-94de1380-a2be-11eb-8e28-23e412abec72.png)

**Comment by fwitte** [comment]
Thank you for the hint, these methods were changed in the 0.4.0 version. It seems, I missed to update the link.

**Comment by fwitte** [comment]
Resolved by #263, you'll see the changes on the master branch with the next version release (scheduled for first week of May).
