### ISSUE TITLE
[website]: Add redirect from /en/master to /en/main

### ISSUE THREAD

**Issue by ChaofanChen** [oemof/tespy#270]
As titled. The website https://tespy.readthedocs.io/en/master/ is gone...

**Comment by fwitte** [comment]
Hi Chaofan,
thank you for reporting. After renaming the master branch to main #265 the link you refer to has indeed vanished (and should not be included in any of the documentation anymore, except I overlooked some places). You can always go tohttps://tespy.readthedocs.io/ which will always redirects to an active version (https://tespy.readthedocs.io/en/main/). I will try to find a way to automatically  redirect .../master/... to .../main/...
Best regards
Francesco

**Comment by fwitte** [comment]
It seems, that the redirect is not possible with the master branch being non-existent... All internal links should be fixed, so time will cure this, I guess :D.
