### ISSUE TITLE
Add tutorial with deleting and adding connections 

### ISSUE THREAD

**Issue by OskarRaftegard** [oemof/tespy#288]
I'm following the heat pump tutorial. When solving the second part of the model, "Valve and evaporator system", I get an error message:   
> "ERROR:root:All Components must have unique labels, duplicate labels are: "valve".  

These are the "dummy-sink" and the real valve component.

1) Somehow I do not think this is expected?
  Setting up the dummy-sink valve as va = Sink('valve')  when modeling the consumer system was supposed to make it easy to replace it when modelling the valve and evaporator.

2) How du you drop / remove / change a component?
The obvious solution above is of course to remove the dummy valve from the code, as soon as the consumer system is verified. But is there a way to delete a component? I could only find a way to delete connectors ( del_conns). 

(Btw, I discovered a Pandas DataFrame, nw.comps. But dropping the row with the dummy did not help. What is this DataFrame?

**Comment by fwitte** [comment]
All issues have been fixed here, closing this.

In case you still have questions/ideas please reach out at any time :)
