### ISSUE TITLE
Help: Geothermal evaporator example

### ISSUE THREAD

**Issue by NicholasFry** [oemof/tespy#292]
Hi @fwitte,

I am reading through your 2020 work on adding an ORC evaporator. I am seeing the specifications for pressure and pressure ratios on the inlet fluids. How are you coming to these values at the start of the model build? Have you already manually calculated the general thermodynamics of the configuration or does this come from an example?
https://tespy.readthedocs.io/en/main/api/tespy.components.html#module-tespy.components.customs.orc_evaporator

```
evaporator.set_attr(pr1=0.95, pr2=0.98, pr3=0.99)
eva_wf_in.set_attr(T=111, p=11,
fluid={'water': 0, 'Isopentane': 1})
eva_steam_in.set_attr(T=147, p=4.3, m=20,
fluid={'water': 1, 'Isopentane': 0})
eva_brine_in.set_attr(T=147, p=10.2, m=190,
fluid={'water': 1, 'Isopentane': 0})
eva_sink_b.set_attr(T=117)
nw.solve(mode='design')
```

It would be easy to determine a wellhead pressure on a fluid for the geothermal brine, but I do not quite understand the fixed working fluid inlet pressure. What is the best course of action if I have the wellhead fluid pressure, the temperature, and the mass flow and I want to build all the rest of the ORC components in TESPy without manually calculating? Can I assume a dT for the working fluid and the rest will be related to the built-in calculations? What is the best way to estimate the pressure ratios - were there empirical curves referenced for the ORC components?

Thank you,
Nick

**Comment by fwitte** [comment]
Hi Nick,
can you write me a message in element or write me an email? I think talking about this over the phone might be helpful. The component was initially created in cooperaiton with @ChaofanChen for the investigation of an ORC power plant powered by a two-phase geothermal heat source, we however took a different approach in the end. The respective publication is still under review.
Have a nice day
Francesco

**Comment by fwitte** [comment]
Closing here, component will be deprecated likely #353
