### ISSUE TITLE
import error 'Network' from 'tespy.networks'

### ISSUE THREAD

**Issue by Narratot** [oemof/tespy#308]
O both Windows and Linux Systems i cannot use the current examples.
I always get the error that the components dows not exist. (I use dedicated anaconda envs for that) But on Google Colab I was able to run the code without issues.

**Comment by Narratot** [comment]
Okay, it works if I use python 3.7. So please indicate the neccessary python version within the installation documentation.

**Comment by fwitte** [comment]
@Narratot, thank you very much for reporting. Can you specify, which python version threw the error with which version of TESPy? Python 3.7 and 3.8 should be allowed, others not (3.9 and higher mainly because CoolProp needs to be installed manually).

best regards

**Comment by fwitte** [comment]
@Narratot: The requirement for python < 3.9 might be dropped soon: https://github.com/oemof/tespy/issues/252
