### ISSUE TITLE
correct assignment of products and educts in component electrolysis

### ISSUE THREAD

**Issue by tub-hofmann** [oemof/tespy#309]
https://github.com/oemof/tespy/blob/51ff17f20c72e848619f9931c1e29f4d890ca9cc/src/tespy/components/reactors/water_electrolyzer.py#L313

O2 and H2 are both products and should have the same sign, or not?

However, the error is not critical, since the enthalpy of formation for oxygen and hydrogen is 0.

**Comment by fwitte** [comment]
Thank you for reporting @tub-hofmann, will be fixed asap.

**Comment by fwitte** [comment]
Closed by #333
