### ISSUE TITLE
A Suspected error when reload the network by using network_reader.load_nwk function

### ISSUE THREAD

**Issue by ShuangChen88** [oemof/tespy#44]
Dear Francesco,

When i was testing my tespy based python script to get the hydraulic results of my network, i got a different computed pipe flow rate results from tespy after reload the network by using nwkr.load_nwk() function, compared with the results directly solved by tespy without reload the network. 

After several testing i found that, if i reset each pipe's hydraulic properties after reload the network by using nwkr.load_nwk() function( in my case i reset them with c.set_attr( hydro_group ='HW')), I could finally re-get the right results from tespy. Based on this finding i am a little doubtful that if the 'hydro_group' of the pipe in my network are not saved in csv file when saving the network. 

I would like to ask you if you could please check that if **the attribute of 'hydro_group' in components** is missing when saving the network and reload the network. 

Best regards and have a good Christmastime!
Shuang

**Comment by fwitte** [comment]
Hi Shuang,
thanks for the report, I will have a look into that next week and give you feedback!
Have a nice weekend!

**Comment by fwitte** [comment]
I will address this bug in #46!
