### ISSUE TITLE
Missing component in COMP_TARGET_CLASSES

### ISSUE THREAD

**Issue by sertomas** [oemof/tespy#508]
When I save and read a network with a DiabaticCombustionChamber I get this error while reading the file: KeyError: 'DiabaticCombustionChamber'. I think this component is missing in network_reader.py/COMP_TARGET_CLASSES. Or is there a reason for that?

**Comment by fwitte** [comment]
@sertomas, could you quickly test, if the changes on branch `fix/#508-missing-imports-in-network-load` make your use case work? Thanks!

**Comment by sertomas** [comment]
Hi @fwitte it works now! :)

**Comment by fwitte** [comment]
@sertomas: I released a new version, which includes the fix. Also, it is now possible to register your own components to the `load_network` method. See the what's new section on the docs. Thanks for reporting the issue!
