### ISSUE TITLE
Saturation function cannot be called on mixtures.

### ISSUE THREAD

**Issue by aljubrmj** [oemof/tespy#516]
I am trying to run this project on geothermal ORC which is highlighted in the tespy documentation. Particularly, I am trying to run the python script [parameter_influence.py](https://github.com/ChaofanChen/ORCSimulator/blob/master/scripts/parameter_influence.py). I get the following error. Can you please support?

`ValueError: Saturation function cannot be called on mixtures.`

**Comment by fwitte** [comment]
Hi @aljubrmj,

what verse of tespy are you using? My guess is, that the mentioned repository is on an older version (hence the requirements.txt file with the version of tespy required for that project). If I can find the time, I will update the other repository and let you know, what the issue was.

Best

**Comment by aljubrmj** [comment]
Hi @fwitte, thank you for the quick response. I am using `tespy-0.7.4`. The mentioned repo is an older version, indeed, which may be causing the error. I would highly appreciate your support in figuring this out. Looking forward.

**Comment by fwitte** [comment]
Hi @aljubrmj.

you can try to use the scripts from this fork+ branch: https://github.com/fwitte/ORCSimulator/tree/update-to-tespy-0.7

They are not yet fully operational, there se, em to be some issues with some of the working fluids, which I could not get behind of in the short time. You can try to dig into it, if you like. All the models should now operational with the latest tespy API in principle. Once that has been figured out, I will adjust the scripts and push the changes to the main repository.

Thank you for reporting the bug! :)

**Comment by fwitte** [comment]
Hi again,

I think I have found the remaining issues with some of the working fluids. It was starting values in the initial simulation, you can check it on the branch I linked before.

Best

Francesco

**Comment by fwitte** [comment]
Closing this issue here, since it has been resolved.

**Comment by aljubrmj** [comment]
Hi Francesco, I just want to say thank you for your efforts. I will let you know if I face any other problems. Cheers
