### ISSUE TITLE
A note should be added to the subsystem docs, that connection and component labels have to be made unique 

### ISSUE THREAD

**Issue by Matt-haug** [oemof/tespy#548]
I have a subsystem than I want to import 2 times in the same network.
However, the Network script raises an error because the same connection connection 2 identical components appears 2 times obviously.
The connections from a Subsystem should be unique for each instance of the same Subsystem, shouldn't they ?

Here is the ValueError that is raised a the 427th line of the tespy/networks/network.py file :

_'There is already a connection with the label f'{c.label}. The connection labels must be unique!'_

**Comment by fwitte** [comment]
Hi @Matt-haug,

can you share a minimal version to replicate the issue? When working with subsystems you should attach something to the labels of components and connections when setting up the class. I usually use the label of the subsystem and concatenate it to the name of each component or connection, e.g. `f'{self.label}_a0'` if the connection name is `a0`. Same approach for components :).

Best

Francesco

**Comment by Matt-haug** [comment]
Hello Francesco,

Thank you for your answer.
I did not think of this option actually ;)

Thanks!
Regards

Mattéo

**Comment by fwitte** [comment]
Maybe I should add a note in the docs, that this is necessary. I will reopen and change the title :). Thank you for reaching out!

**Comment by fwitte** [comment]
Closed as completed by #553
