### ISSUE TITLE
BUG: Incorrect syntax  in the filename by using tespy_fluid feature in Windows

### ISSUE THREAD

**Issue by ShuangChen88** [oemof/tespy#56]
When trying to use the feature tespy_fluid in Windows system, a error report from os comes out to point that a incorrect syntax is in the filename. it is suspect that it may be a bug for Windows, since Windows could not create a folder containing the name with character":". Please have a check about this issue. Thanks.

**Comment by fwitte** [comment]
Hi Shuang,
thanks for reporting. I will address that issue in the next release.
Have a nice week!

**Comment by ShuangChen88** [comment]
Hi Francesco,

I have already send you a pull request for solving this issue in #57. Please have a check for it when you get a free time.

Have a nice week!

**Comment by fwitte** [comment]
Thanks for your contribution, I merged the PR.
