### ISSUE TITLE
a bug of setting 'm'(not be allowed) of conn automatically, while calculating a plant model under offdesign condition circularly 

### ISSUE THREAD

**Issue by legendary-zju** [oemof/tespy#578]
Deer creater:
      I need your help. I construct a plant class as well as your public instance (Thermal Power Plant Efficiency Optimization). The construction and the param setting is same as the instance, but i add the fitted curve on the turbine and condenser under offdesign condition. When i apply the model in loop calculation, a bizarre bug appears. If the error [**Pressure to PQ_flash [6.03105e+07 Pa] must be in range [ 611.655 Pa, 2.2064e+07 Pa]) .**] and [**unable to solve 1phase PY flash with Tmin=270.847, Tmax=3000 due to error: HSU_P_flash_singlephase_Brent could not find a solution because Smolar [200.416 J/mol/K] is above the maximum value of 175.884081765 J/mol/K**] appears in the offdesign solve in the loop calculation, then the mass flow will be set on a blank connection by the code automatically, the subsequent calculation will break due to the error [**You cannot specify two or more values for mass flow in the same linear branch (starting at merge2 and ending at cycle closer).**]
      This phenomenon only appears under offdesign condition, the loop calculation under design condition has no problem. I have spent 7 days on looking for the reason, but nothing has been found. Can you help me ?

**Comment by legendary-zju** [comment]
And another error [**The mass fraction of a single fluid cannot be specified twice within a branch.**] will also appears sometimes , then the loop calculation will be broke down. May the error be documented lead to the param setting ? I don't konw.....

**Comment by fwitte** [comment]
Hi @legendary-zju,

In case a simulation crashed (e.g. due to an error in coolprop), you have to call a function to reset some presolving artifacts, see: https://tespy.readthedocs.io/en/main/tutorials/starting_values.html#tespy-tutorial-starting-values-label.

```python
try:
    nw.solve("design")
except ValueError as e:
    print(e)
    nw.reset_topology_reduction_specifications()
```

This behavior will change with the next major refactoring, for the meantime you have to do it in this way.

Best 

Francesco

**Comment by fwitte** [comment]
Perfect, closing this issue then
