### ISSUE TITLE
Download page not working

### ISSUE THREAD

**Issue by mrahjoo** [oemof/tespy#582]
The documentation downloads section appears to be disabled or not showing any documents, despite the project documentation stating that different formats (PDF, HTML, and ePub) should be available.

![Screenshot](https://github.com/user-attachments/assets/29d5bc50-b7ff-499c-9b49-1f5052e7eaf7)

**Comment by fwitte** [comment]
Hi @mrahjoo,

thank you for reporting. I will delete the references from the documentation. There was once a pdf version (of the online website), but it stopped working at some point so I disabled it.

Best

Francesco

**Comment by fwitte** [comment]
Solved by [97726da](https://github.com/oemof/tespy/commit/97726da7939c0334af882ab97e09d73a4ab079d3)
