### ISSUE TITLE
Superheater control via expansion valve

### ISSUE THREAD

**Issue by dkeiner** [oemof/tespy#63]
Hello,
for a study research project I try to model a heat pump with tespy. On the whole it looks quite good, except that my resulting COP's are a little bit lower than for heat pumps at similar power ranges (about 10 - 15 kW_th). In my opinion, one main reason could be that I didn't implement the superheater yet, as heat pumps control them via the expansion valve, which is not possible in the tespy model.
Is it possible to realize that somehow with the current release? Help would be very appreciated.

**Comment by fwitte** [comment]
Hi @dkeiner,
thanks for your message, I am happy to hear that!
I think it would be best, if you send a sketch of you plant with and without superheater alongside with your code, so we can discuss the implementation. If you want, you can write me an e-mail, so we can discuss this over the phone/skype etc..
Have a nice evening!
Francesco

**Comment by fwitte** [comment]
@dkeiner, you do not mean this by chance: #64?

**Comment by fwitte** [comment]
Is this issue still relevant? If this is the case, feel free to reopen :)!
